### ISSUE TITLE
Remove "OpenWhisk" from Documentation page title (redundant)

### ISSUE THREAD

**Issue by mrutkows** [pritidesai/openwhisk-website#73]

**Comment by mrutkows** [comment]
and causes spacing issues with header line heights, as well as pushes first text well off the screen vertically.

**Comment by mrutkows** [comment]
Attempt to play with the "terminal" style (require scrolling) but not text around it.

**Comment by pritidesai** [comment]
this is fixed, we do not have "OpenWhisk" on the documentation page title.
